// Package xo_models contains the types for schema 'dev_themiseum'.
package xo_models

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql/driver"
	"errors"
)

// Access is the 'access' enum type from schema 'dev_themiseum'.
type Access uint16

const (
	// AccessPrivate is the 'private' Access.
	AccessPrivate = Access(1)

	// AccessPublic is the 'public' Access.
	AccessPublic = Access(2)
)

// String returns the string value of the Access.
func (a Access) String() string {
	var enumVal string

	switch a {
	case AccessPrivate:
		enumVal = "private"

	case AccessPublic:
		enumVal = "public"
	}

	return enumVal
}

// MarshalText marshals Access into text.
func (a Access) MarshalText() ([]byte, error) {
	return []byte(a.String()), nil
}

// UnmarshalText unmarshals Access from text.
func (a *Access) UnmarshalText(text []byte) error {
	switch string(text) {
	case "private":
		*a = AccessPrivate

	case "public":
		*a = AccessPublic

	default:
		return errors.New("invalid Access")
	}

	return nil
}

// Value satisfies the sql/driver.Valuer interface for Access.
func (a Access) Value() (driver.Value, error) {
	return a.String(), nil
}

// Scan satisfies the database/sql.Scanner interface for Access.
func (a *Access) Scan(src interface{}) error {
	buf, ok := src.([]byte)
	if !ok {
		return errors.New("invalid Access")
	}

	return a.UnmarshalText(buf)
}
