// Package xo_models contains the types for schema 'dev_themiseum'.
package xo_models

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql/driver"
	"errors"
)

// Name is the 'name' enum type from schema 'dev_themiseum'.
type Name uint16

const (
	// NameSwarm is the 'swarm' Name.
	NameSwarm = Name(1)

	// NameS3 is the 's3' Name.
	NameS3 = Name(2)
)

// String returns the string value of the Name.
func (n Name) String() string {
	var enumVal string

	switch n {
	case NameSwarm:
		enumVal = "swarm"

	case NameS3:
		enumVal = "s3"
	}

	return enumVal
}

// MarshalText marshals Name into text.
func (n Name) MarshalText() ([]byte, error) {
	return []byte(n.String()), nil
}

// UnmarshalText unmarshals Name from text.
func (n *Name) UnmarshalText(text []byte) error {
	switch string(text) {
	case "swarm":
		*n = NameSwarm

	case "s3":
		*n = NameS3

	default:
		return errors.New("invalid Name")
	}

	return nil
}

// Value satisfies the sql/driver.Valuer interface for Name.
func (n Name) Value() (driver.Value, error) {
	return n.String(), nil
}

// Scan satisfies the database/sql.Scanner interface for Name.
func (n *Name) Scan(src interface{}) error {
	buf, ok := src.([]byte)
	if !ok {
		return errors.New("invalid Name")
	}

	return n.UnmarshalText(buf)
}
