// Package xo_models contains the types for schema 'dev_themiseum'.
package xo_models

// Code generated by xo. DO NOT EDIT.

// SomeFile represents a row from 'dev_themiseum.some_files'.
type SomeFile struct {
	ID       int    `json:"id"`        // id
	FileHash string `json:"file_hash"` // file_hash
}
