// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Files         string
	FilesLabels   string
	FilesStorages string
	Labels        string
	Notifications string
	Storages      string
}{
	Files:         "files",
	FilesLabels:   "files_labels",
	FilesStorages: "files_storages",
	Labels:        "labels",
	Notifications: "notifications",
	Storages:      "storages",
}
