// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/pkg/errors"
	"github.com/volatiletech/null"
	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/queries/qm"
	"github.com/volatiletech/sqlboiler/strmangle"
)

// FilesStorage is an object representing the database table.
type FilesStorage struct {
	ID         int       `boil:"id" json:"id" toml:"id" yaml:"id"`
	FileID     int       `boil:"file_id" json:"file_id" toml:"file_id" yaml:"file_id"`
	StorageID  null.Int  `boil:"storage_id" json:"storage_id,omitempty" toml:"storage_id" yaml:"storage_id,omitempty"`
	CreateTime time.Time `boil:"create_time" json:"create_time" toml:"create_time" yaml:"create_time"`
	UpdateTime time.Time `boil:"update_time" json:"update_time" toml:"update_time" yaml:"update_time"`

	R *filesStorageR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L filesStorageL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var FilesStorageColumns = struct {
	ID         string
	FileID     string
	StorageID  string
	CreateTime string
	UpdateTime string
}{
	ID:         "id",
	FileID:     "file_id",
	StorageID:  "storage_id",
	CreateTime: "create_time",
	UpdateTime: "update_time",
}

// FilesStorageRels is where relationship names are stored.
var FilesStorageRels = struct {
	File    string
	Storage string
}{
	File:    "File",
	Storage: "Storage",
}

// filesStorageR is where relationships are stored.
type filesStorageR struct {
	File    *File
	Storage *Storage
}

// NewStruct creates a new relationship struct
func (*filesStorageR) NewStruct() *filesStorageR {
	return &filesStorageR{}
}

// filesStorageL is where Load methods for each relationship are stored.
type filesStorageL struct{}

var (
	filesStorageColumns               = []string{"id", "file_id", "storage_id", "create_time", "update_time"}
	filesStorageColumnsWithoutDefault = []string{"file_id", "storage_id"}
	filesStorageColumnsWithDefault    = []string{"id", "create_time", "update_time"}
	filesStoragePrimaryKeyColumns     = []string{"id"}
)

type (
	// FilesStorageSlice is an alias for a slice of pointers to FilesStorage.
	// This should generally be used opposed to []FilesStorage.
	FilesStorageSlice []*FilesStorage
	// FilesStorageHook is the signature for custom FilesStorage hook methods
	FilesStorageHook func(boil.Executor, *FilesStorage) error

	filesStorageQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	filesStorageType                 = reflect.TypeOf(&FilesStorage{})
	filesStorageMapping              = queries.MakeStructMapping(filesStorageType)
	filesStoragePrimaryKeyMapping, _ = queries.BindMapping(filesStorageType, filesStorageMapping, filesStoragePrimaryKeyColumns)
	filesStorageInsertCacheMut       sync.RWMutex
	filesStorageInsertCache          = make(map[string]insertCache)
	filesStorageUpdateCacheMut       sync.RWMutex
	filesStorageUpdateCache          = make(map[string]updateCache)
	filesStorageUpsertCacheMut       sync.RWMutex
	filesStorageUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
)

var filesStorageBeforeInsertHooks []FilesStorageHook
var filesStorageBeforeUpdateHooks []FilesStorageHook
var filesStorageBeforeDeleteHooks []FilesStorageHook
var filesStorageBeforeUpsertHooks []FilesStorageHook

var filesStorageAfterInsertHooks []FilesStorageHook
var filesStorageAfterSelectHooks []FilesStorageHook
var filesStorageAfterUpdateHooks []FilesStorageHook
var filesStorageAfterDeleteHooks []FilesStorageHook
var filesStorageAfterUpsertHooks []FilesStorageHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *FilesStorage) doBeforeInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range filesStorageBeforeInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *FilesStorage) doBeforeUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range filesStorageBeforeUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *FilesStorage) doBeforeDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range filesStorageBeforeDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *FilesStorage) doBeforeUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range filesStorageBeforeUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *FilesStorage) doAfterInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range filesStorageAfterInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *FilesStorage) doAfterSelectHooks(exec boil.Executor) (err error) {
	for _, hook := range filesStorageAfterSelectHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *FilesStorage) doAfterUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range filesStorageAfterUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *FilesStorage) doAfterDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range filesStorageAfterDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *FilesStorage) doAfterUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range filesStorageAfterUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddFilesStorageHook registers your hook function for all future operations.
func AddFilesStorageHook(hookPoint boil.HookPoint, filesStorageHook FilesStorageHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		filesStorageBeforeInsertHooks = append(filesStorageBeforeInsertHooks, filesStorageHook)
	case boil.BeforeUpdateHook:
		filesStorageBeforeUpdateHooks = append(filesStorageBeforeUpdateHooks, filesStorageHook)
	case boil.BeforeDeleteHook:
		filesStorageBeforeDeleteHooks = append(filesStorageBeforeDeleteHooks, filesStorageHook)
	case boil.BeforeUpsertHook:
		filesStorageBeforeUpsertHooks = append(filesStorageBeforeUpsertHooks, filesStorageHook)
	case boil.AfterInsertHook:
		filesStorageAfterInsertHooks = append(filesStorageAfterInsertHooks, filesStorageHook)
	case boil.AfterSelectHook:
		filesStorageAfterSelectHooks = append(filesStorageAfterSelectHooks, filesStorageHook)
	case boil.AfterUpdateHook:
		filesStorageAfterUpdateHooks = append(filesStorageAfterUpdateHooks, filesStorageHook)
	case boil.AfterDeleteHook:
		filesStorageAfterDeleteHooks = append(filesStorageAfterDeleteHooks, filesStorageHook)
	case boil.AfterUpsertHook:
		filesStorageAfterUpsertHooks = append(filesStorageAfterUpsertHooks, filesStorageHook)
	}
}

// One returns a single filesStorage record from the query.
func (q filesStorageQuery) One(exec boil.Executor) (*FilesStorage, error) {
	o := &FilesStorage{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(nil, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for files_storages")
	}

	if err := o.doAfterSelectHooks(exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all FilesStorage records from the query.
func (q filesStorageQuery) All(exec boil.Executor) (FilesStorageSlice, error) {
	var o []*FilesStorage

	err := q.Bind(nil, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to FilesStorage slice")
	}

	if len(filesStorageAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all FilesStorage records in the query.
func (q filesStorageQuery) Count(exec boil.Executor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRow(exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count files_storages rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q filesStorageQuery) Exists(exec boil.Executor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRow(exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if files_storages exists")
	}

	return count > 0, nil
}

// File pointed to by the foreign key.
func (o *FilesStorage) File(mods ...qm.QueryMod) fileQuery {
	queryMods := []qm.QueryMod{
		qm.Where("id=?", o.FileID),
	}

	queryMods = append(queryMods, mods...)

	query := Files(queryMods...)
	queries.SetFrom(query.Query, "`files`")

	return query
}

// Storage pointed to by the foreign key.
func (o *FilesStorage) Storage(mods ...qm.QueryMod) storageQuery {
	queryMods := []qm.QueryMod{
		qm.Where("id=?", o.StorageID),
	}

	queryMods = append(queryMods, mods...)

	query := Storages(queryMods...)
	queries.SetFrom(query.Query, "`storages`")

	return query
}

// LoadFile allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (filesStorageL) LoadFile(e boil.Executor, singular bool, maybeFilesStorage interface{}, mods queries.Applicator) error {
	var slice []*FilesStorage
	var object *FilesStorage

	if singular {
		object = maybeFilesStorage.(*FilesStorage)
	} else {
		slice = *maybeFilesStorage.(*[]*FilesStorage)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &filesStorageR{}
		}
		args = append(args, object.FileID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &filesStorageR{}
			}

			for _, a := range args {
				if a == obj.FileID {
					continue Outer
				}
			}

			args = append(args, obj.FileID)

		}
	}

	query := NewQuery(qm.From(`files`), qm.WhereIn(`id in ?`, args...))
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.Query(e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load File")
	}

	var resultSlice []*File
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice File")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for files")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for files")
	}

	if len(filesStorageAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.File = foreign
		if foreign.R == nil {
			foreign.R = &fileR{}
		}
		foreign.R.FilesStorages = append(foreign.R.FilesStorages, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.FileID == foreign.ID {
				local.R.File = foreign
				if foreign.R == nil {
					foreign.R = &fileR{}
				}
				foreign.R.FilesStorages = append(foreign.R.FilesStorages, local)
				break
			}
		}
	}

	return nil
}

// LoadStorage allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (filesStorageL) LoadStorage(e boil.Executor, singular bool, maybeFilesStorage interface{}, mods queries.Applicator) error {
	var slice []*FilesStorage
	var object *FilesStorage

	if singular {
		object = maybeFilesStorage.(*FilesStorage)
	} else {
		slice = *maybeFilesStorage.(*[]*FilesStorage)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &filesStorageR{}
		}
		if !queries.IsNil(object.StorageID) {
			args = append(args, object.StorageID)
		}

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &filesStorageR{}
			}

			for _, a := range args {
				if queries.Equal(a, obj.StorageID) {
					continue Outer
				}
			}

			if !queries.IsNil(obj.StorageID) {
				args = append(args, obj.StorageID)
			}

		}
	}

	query := NewQuery(qm.From(`storages`), qm.WhereIn(`id in ?`, args...))
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.Query(e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Storage")
	}

	var resultSlice []*Storage
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Storage")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for storages")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for storages")
	}

	if len(filesStorageAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Storage = foreign
		if foreign.R == nil {
			foreign.R = &storageR{}
		}
		foreign.R.FilesStorages = append(foreign.R.FilesStorages, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.StorageID, foreign.ID) {
				local.R.Storage = foreign
				if foreign.R == nil {
					foreign.R = &storageR{}
				}
				foreign.R.FilesStorages = append(foreign.R.FilesStorages, local)
				break
			}
		}
	}

	return nil
}

// SetFile of the filesStorage to the related item.
// Sets o.R.File to related.
// Adds o to related.R.FilesStorages.
func (o *FilesStorage) SetFile(exec boil.Executor, insert bool, related *File) error {
	var err error
	if insert {
		if err = related.Insert(exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `files_storages` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"file_id"}),
		strmangle.WhereClause("`", "`", 0, filesStoragePrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, updateQuery)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	if _, err = exec.Exec(updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.FileID = related.ID
	if o.R == nil {
		o.R = &filesStorageR{
			File: related,
		}
	} else {
		o.R.File = related
	}

	if related.R == nil {
		related.R = &fileR{
			FilesStorages: FilesStorageSlice{o},
		}
	} else {
		related.R.FilesStorages = append(related.R.FilesStorages, o)
	}

	return nil
}

// SetStorage of the filesStorage to the related item.
// Sets o.R.Storage to related.
// Adds o to related.R.FilesStorages.
func (o *FilesStorage) SetStorage(exec boil.Executor, insert bool, related *Storage) error {
	var err error
	if insert {
		if err = related.Insert(exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `files_storages` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"storage_id"}),
		strmangle.WhereClause("`", "`", 0, filesStoragePrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, updateQuery)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	if _, err = exec.Exec(updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.StorageID, related.ID)
	if o.R == nil {
		o.R = &filesStorageR{
			Storage: related,
		}
	} else {
		o.R.Storage = related
	}

	if related.R == nil {
		related.R = &storageR{
			FilesStorages: FilesStorageSlice{o},
		}
	} else {
		related.R.FilesStorages = append(related.R.FilesStorages, o)
	}

	return nil
}

// RemoveStorage relationship.
// Sets o.R.Storage to nil.
// Removes o from all passed in related items' relationships struct (Optional).
func (o *FilesStorage) RemoveStorage(exec boil.Executor, related *Storage) error {
	var err error

	queries.SetScanner(&o.StorageID, nil)
	if _, err = o.Update(exec, boil.Whitelist("storage_id")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.R.Storage = nil
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.FilesStorages {
		if queries.Equal(o.StorageID, ri.StorageID) {
			continue
		}

		ln := len(related.R.FilesStorages)
		if ln > 1 && i < ln-1 {
			related.R.FilesStorages[i] = related.R.FilesStorages[ln-1]
		}
		related.R.FilesStorages = related.R.FilesStorages[:ln-1]
		break
	}
	return nil
}

// FilesStorages retrieves all the records using an executor.
func FilesStorages(mods ...qm.QueryMod) filesStorageQuery {
	mods = append(mods, qm.From("`files_storages`"))
	return filesStorageQuery{NewQuery(mods...)}
}

// FindFilesStorage retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindFilesStorage(exec boil.Executor, iD int, selectCols ...string) (*FilesStorage, error) {
	filesStorageObj := &FilesStorage{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `files_storages` where `id`=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(nil, exec, filesStorageObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from files_storages")
	}

	return filesStorageObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *FilesStorage) Insert(exec boil.Executor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no files_storages provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(filesStorageColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	filesStorageInsertCacheMut.RLock()
	cache, cached := filesStorageInsertCache[key]
	filesStorageInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			filesStorageColumns,
			filesStorageColumnsWithDefault,
			filesStorageColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(filesStorageType, filesStorageMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(filesStorageType, filesStorageMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `files_storages` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `files_storages` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `files_storages` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, filesStoragePrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	result, err := exec.Exec(cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into files_storages")
	}

	var lastID int64
	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == filesStorageMapping["ID"] {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.retQuery)
		fmt.Fprintln(boil.DebugWriter, identifierCols...)
	}

	err = exec.QueryRow(cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for files_storages")
	}

CacheNoHooks:
	if !cached {
		filesStorageInsertCacheMut.Lock()
		filesStorageInsertCache[key] = cache
		filesStorageInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(exec)
}

// Update uses an executor to update the FilesStorage.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *FilesStorage) Update(exec boil.Executor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	filesStorageUpdateCacheMut.RLock()
	cache, cached := filesStorageUpdateCache[key]
	filesStorageUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			filesStorageColumns,
			filesStoragePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update files_storages, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `files_storages` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, filesStoragePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(filesStorageType, filesStorageMapping, append(wl, filesStoragePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	var result sql.Result
	result, err = exec.Exec(cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update files_storages row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for files_storages")
	}

	if !cached {
		filesStorageUpdateCacheMut.Lock()
		filesStorageUpdateCache[key] = cache
		filesStorageUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(exec)
}

// UpdateAll updates all rows with the specified column values.
func (q filesStorageQuery) UpdateAll(exec boil.Executor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.Exec(exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for files_storages")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for files_storages")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o FilesStorageSlice) UpdateAll(exec boil.Executor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), filesStoragePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `files_storages` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, filesStoragePrimaryKeyColumns, len(o)))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	result, err := exec.Exec(sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in filesStorage slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all filesStorage")
	}
	return rowsAff, nil
}

var mySQLFilesStorageUniqueColumns = []string{
	"id",
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *FilesStorage) Upsert(exec boil.Executor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no files_storages provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(filesStorageColumnsWithDefault, o)
	nzUniques := queries.NonZeroDefaultSet(mySQLFilesStorageUniqueColumns, o)

	if len(nzUniques) == 0 {
		return errors.New("cannot upsert with a table that cannot conflict on a unique column")
	}

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzUniques {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	filesStorageUpsertCacheMut.RLock()
	cache, cached := filesStorageUpsertCache[key]
	filesStorageUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			filesStorageColumns,
			filesStorageColumnsWithDefault,
			filesStorageColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			filesStorageColumns,
			filesStoragePrimaryKeyColumns,
		)

		if len(update) == 0 {
			return errors.New("models: unable to upsert files_storages, could not build update column list")
		}

		ret = strmangle.SetComplement(ret, nzUniques)
		cache.query = buildUpsertQueryMySQL(dialect, "files_storages", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `files_storages` WHERE %s",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
			strmangle.WhereClause("`", "`", 0, nzUniques),
		)

		cache.valueMapping, err = queries.BindMapping(filesStorageType, filesStorageMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(filesStorageType, filesStorageMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	result, err := exec.Exec(cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to upsert for files_storages")
	}

	var lastID int64
	var uniqueMap []uint64
	var nzUniqueCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == filesStorageMapping["id"] {
		goto CacheNoHooks
	}

	uniqueMap, err = queries.BindMapping(filesStorageType, filesStorageMapping, nzUniques)
	if err != nil {
		return errors.Wrap(err, "models: unable to retrieve unique values for files_storages")
	}
	nzUniqueCols = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), uniqueMap)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.retQuery)
		fmt.Fprintln(boil.DebugWriter, nzUniqueCols...)
	}

	err = exec.QueryRow(cache.retQuery, nzUniqueCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for files_storages")
	}

CacheNoHooks:
	if !cached {
		filesStorageUpsertCacheMut.Lock()
		filesStorageUpsertCache[key] = cache
		filesStorageUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(exec)
}

// Delete deletes a single FilesStorage record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *FilesStorage) Delete(exec boil.Executor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no FilesStorage provided for delete")
	}

	if err := o.doBeforeDeleteHooks(exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), filesStoragePrimaryKeyMapping)
	sql := "DELETE FROM `files_storages` WHERE `id`=?"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	result, err := exec.Exec(sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from files_storages")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for files_storages")
	}

	if err := o.doAfterDeleteHooks(exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q filesStorageQuery) DeleteAll(exec boil.Executor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no filesStorageQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.Exec(exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from files_storages")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for files_storages")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o FilesStorageSlice) DeleteAll(exec boil.Executor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no FilesStorage slice provided for delete all")
	}

	if len(o) == 0 {
		return 0, nil
	}

	if len(filesStorageBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), filesStoragePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `files_storages` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, filesStoragePrimaryKeyColumns, len(o))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}

	result, err := exec.Exec(sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from filesStorage slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for files_storages")
	}

	if len(filesStorageAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *FilesStorage) Reload(exec boil.Executor) error {
	ret, err := FindFilesStorage(exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *FilesStorageSlice) ReloadAll(exec boil.Executor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := FilesStorageSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), filesStoragePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `files_storages`.* FROM `files_storages` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, filesStoragePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(nil, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in FilesStorageSlice")
	}

	*o = slice

	return nil
}

// FilesStorageExists checks if the FilesStorage row exists.
func FilesStorageExists(exec boil.Executor, iD int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `files_storages` where `id`=? limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, iD)
	}

	row := exec.QueryRow(sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if files_storages exists")
	}

	return exists, nil
}
